# Experiment: 07



# Neural Network Using Scikit Learn

In [ ]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import sklearn

from sklearn.neural_network import MLPClassifier

from sklearn.neural_network import MLPRegressor

# Import necessary modules

from sklearn.model_selection import train_test_split

from sklearn.metrics import mean_squared_error

from math import sqrt

from sklearn.metrics import r2_score

In [3]:
from sklearn import datasets
df = pd.read_csv('diabetes.csv')

print(df.shape)

df.describe().transpose()

(768, 9)


count        mean         std     min       25%  \
Pregnancies               768.0    3.845052    3.369578   0.000   1.00000   
Glucose                   768.0  120.894531   31.972618   0.000  99.00000   
BloodPressure             768.0   69.105469   19.355807   0.000  62.00000   
SkinThickness             768.0   20.536458   15.952218   0.000   0.00000   
Insulin                   768.0   79.799479  115.244002   0.000   0.00000   
BMI                       768.0   31.992578    7.884160   0.000  27.30000   
DiabetesPedigreeFunction  768.0    0.471876    0.331329   0.078   0.24375   
Age                       768.0   33.240885   11.760232  21.000  24.00000   
Outcome                   768.0    0.348958    0.476951   0.000   0.00000   

                               50%        75%     max  
Pregnancies                 3.0000    6.00000   17.00  
Glucose                   117.0000  140.25000  199.00  
BloodPressure              72.0000   80.00000  122.00  
SkinThickness              23.0000   32.00000   99.00  
Insulin                    30.5000  127.25000  846.00  
BMI                        32.0000   36.60000   67.10  
DiabetesPedigreeFunction    0.3725    0.62625    2.42  
Age                        29.0000   41.00000   81.00  
Outcome                     0.0000    1.00000    1.00

In [4]:
target_column = ['Age']

predictors = list(set(list(df.columns))-set(target_column))

df[predictors] = df[predictors]/df[predictors].max()

df.describe().transpose()

count       mean        std        min        25%  \
Pregnancies               768.0   0.226180   0.198210   0.000000   0.058824   
Glucose                   768.0   0.607510   0.160666   0.000000   0.497487   
BloodPressure             768.0   0.566438   0.158654   0.000000   0.508197   
SkinThickness             768.0   0.207439   0.161134   0.000000   0.000000   
Insulin                   768.0   0.094326   0.136222   0.000000   0.000000   
BMI                       768.0   0.476790   0.117499   0.000000   0.406855   
DiabetesPedigreeFunction  768.0   0.194990   0.136913   0.032231   0.100723   
Age                       768.0  33.240885  11.760232  21.000000  24.000000   
Outcome                   768.0   0.348958   0.476951   0.000000   0.000000   

                                50%        75%   max  
Pregnancies                0.176471   0.352941   1.0  
Glucose                    0.587940   0.704774   1.0  
BloodPressure              0.590164   0.655738   1.0  
SkinThickness              0.232323   0.323232   1.0  
Insulin                    0.036052   0.150414   1.0  
BMI                        0.476900   0.545455   1.0  
DiabetesPedigreeFunction   0.153926   0.258781   1.0  
Age                       29.000000  41.000000  81.0  
Outcome                    0.000000   1.000000   1.0

In [5]:
X = df[predictors].values

y = df[target_column].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=40)

print(X_train.shape); print(X_test.shape)

(537, 8)
(231, 8)


In [6]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='relu', solver='adam', max_iter=500)

mlp.fit(X_train,y_train)

predict_train = mlp.predict(X_train)

predict_test = mlp.predict(X_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [7]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
              precision    recall  f1-score   support

          21       0.00      0.00      0.00        48
          22       0.00      0.00      0.00        48
          23       0.00      0.00      0.00        28
          24       0.07      1.00      0.14        39
          25       0.00      0.00      0.00        31
          26       0.00      0.00      0.00        27
          27       0.00      0.00      0.00        20
          28       0.00      0.00      0.00        23
          29       0.00      0.00      0.00        24
          30       0.00      0.00      0.00        13
          31       0.00      0.00      0.00        17
          32       0.00      0.00      0.00         9
          33       0.00      0.00      0.00        15
          34       0.00      0.00      0.00        11
          35       0.00      0.00      0.00         8
          36   

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [8]:
print(confusion_matrix(y_test,predict_test))

print(classification_report(y_test,predict_test))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
              precision    recall  f1-score   support

          21       0.00      0.00      0.00        15
          22       0.00      0.00      0.00        24
          23       0.00      0.00      0.00        10
          24       0.03      1.00      0.06         7
          25       0.00      0.00      0.00        17
          26       0.00      0.00      0.00         6
          27       0.00      0.00      0.00        12
          28       0.00      0.00      0.00        12
          29       0.00      0.00      0.00         5
          30       0.00      0.00      0.00         8
          31       0.00      0.00      0.00         7
          32       0.00      0.00      0.00         7
          33       0.00      0.00      0.00         2
          34       0.00      0.00      0.00         3
          35       0.00      0.00      0.00         2
          36   